CREATE TABLE collections (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    drink_name TEXT NOT NULL,
    main_liquor TEXT NOT NULL,
    ingredients TEXT NOT NULL,
    instructions TEXT NOT NULL,
    created TIMESTAMP DEFAULT now() NOT NULL
);