INSERT INTO collections (drink_name, main_liquor, ingredients, instructions)
VALUES  
    ('Pink Lemonade Cocktail', 'Vodka', '2 cups ice, (3/4 cup) Vodka, (1/3 cup) Lime juice, (1/3 cup) Cranberry juice, (1/4 cup) Malibu, 1.25 quart Lemonade OR Sprite','Combine all of the ingredients in a large pitcher filled with ice, adding the soda last. Serve!'),
    ('Cosmopolitan', 'Vodka', '1 1/2 ounces vodka (or citrus vodka), 1 ounce Cointreau orange liqueur, 1/2 ounce fresh lime juice, 1/4 ounce cranberry juice, Garnish: orange peel', 'Shake the ingredients with ice in a cocktail shaker, strain into a chilled cocktail glass and add orange peel garnish.'),
    ('Margarita', 'Tequila', '2 ounces blanco tequila, Juice of 1 whole lime, 1/2 ounce Triple Sec, Salt or sugar for rim (optional), Lime wedge, for garnish', 'Fill a cocktail shaker with ice and add tequila, lime juice and triple sec. Shake. Pour, with the ice, into a glass (with a salt or sugar rim). Garnish with wedge of lime.'),
    ('Tequila Sunrise', 'Tequila', '1 1/2 ounces tequila, 3/4 cup orange juice, 3/4 ounce grenadine syrup, Orange slice, for garnish, Maraschino cherry, for garnish', 'In a glass filled with ice, pour in the tequila and orange juice. Slowly pour the grenadine into the glass over the back of a spoon or by drizzling it down the side of the glass, allowing it to settle at the bottom. Garnish with an orange slice and maraschino cherry.'),
    ('Piña Colada', 'Rum', '2 1/2 oz. Rum, 3 oz. pineapple juice, 1 oz. coconut cream, Ice', 'Start with the rum. Then combine with unsweetened pineapple juice, and coconut cream in a blender. Blend on high with a cup or so of crushed ice, or 5 or 6 ice cubes. Pour into a tall glass. Garnish with whatever you''ve got'),
    ('Mojito', 'Rum', '2 oz. White Rum, 1/2 oz. lime juice (squeezed fresh), 1 tsp. superfine sugar, 3 mint leaves, Club soda or Seltzer', 'In a small glass, muddle lime juice with 1/2 to 1 tsp. superfine sugar. Add the mint leaves, mushing them against the side of the glass. Fill glass 2/3 with cracked ice and pour in the rum. Pitch in the squeezed-out lime shell and top off with club soda or seltzer.'),
    ('Scotch Sour', 'Scotch', '1 1/2 ounces Scotch whisky (blended), 3/4 ounce lemon juice (fresh)', 'Gather the ingredients. In a cocktail shaker filled with ice, pour the scotch and lemon juice. Shake well. Strain into a glass filled with fresh ice.'),
    ('Strawberry Scotch Smash', 'Scotch', '1 strawberry, chopped or mashed, Pinch mint leaves, 1 1/2 oz lemon juice, 1 1/2 oz simple syrup, 3 oz Jameson, Ice, for serving', 'Place all ingredients in a cocktail shaker. Shake vigorously. Pour into a glass filled with ice and garnish with mint and a strawberry.'),
    ('Gin & Tonic', 'Gin', 'Ice cubes, 2 ounces gin, 4 to 5​ ounces tonic water, Garnish:​ lime wedge', 'Gather the ingredients. In a  glass filled with ice cubes, pour the gin, then top with tonic. Gently stir to combine, but not so much so that you lose carbonation. Garnish with a lime wedge.'),
    ('Dirty Martini', 'Gin', '2 1/2 ounces gin or vodka, 1/2 ounce dry vermouth, 1/2 ounce olive brine, Garnish: 2 to 4 olives', 'Add all the ingredients into a mixing glass with ice and stir. Strain into a chilled cocktail glass. Garnish with 2 to 4 olives, skewered.')
;